CREATE INDEX "idx_challenge_repos_challenge_id" ON "challenge_repos" USING btree ("challenge_id");--> statement-breakpoint
CREATE INDEX "idx_challenge_repos_repo_id" ON "challenge_repos" USING btree ("repo_id");--> statement-breakpoint
CREATE INDEX "idx_challenge_repos_composite" ON "challenge_repos" USING btree ("challenge_id","repo_id");--> statement-breakpoint
CREATE INDEX "idx_challenge_teams_challenge_id" ON "challenge_teams" USING btree ("challenge_id");--> statement-breakpoint
CREATE INDEX "idx_challenge_teams_user_id" ON "challenge_teams" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_challenge_teams_composite" ON "challenge_teams" USING btree ("challenge_id","user_id");--> statement-breakpoint
CREATE INDEX "idx_challenges_project_id" ON "challenges" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "idx_challenges_status" ON "challenges" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_contributions_challenge_id" ON "contributions" USING btree ("challenge_id");--> statement-breakpoint
CREATE INDEX "idx_contributions_user_id" ON "contributions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_evaluation_grid_categories_grid_id" ON "evaluation_grid_categories" USING btree ("grid_id");--> statement-breakpoint
CREATE INDEX "idx_evaluation_grid_categories_position" ON "evaluation_grid_categories" USING btree ("grid_id","position");--> statement-breakpoint
CREATE INDEX "idx_evaluation_grid_subcriteria_category_id" ON "evaluation_grid_subcriteria" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "idx_evaluation_grid_subcriteria_position" ON "evaluation_grid_subcriteria" USING btree ("category_id","position");--> statement-breakpoint
CREATE INDEX "idx_evaluation_grids_status" ON "evaluation_grids" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_evaluation_grids_updated_at" ON "evaluation_grids" USING btree ("updated_at");--> statement-breakpoint
CREATE INDEX "idx_evaluation_grids_slug_status" ON "evaluation_grids" USING btree ("slug","status");--> statement-breakpoint
CREATE INDEX "idx_eval_run_contributions_run_id" ON "evaluation_run_contributions" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX "idx_eval_run_contributions_contribution_id" ON "evaluation_run_contributions" USING btree ("contribution_id");--> statement-breakpoint
CREATE INDEX "idx_eval_run_contributions_run_status" ON "evaluation_run_contributions" USING btree ("run_id","status");--> statement-breakpoint
CREATE INDEX "idx_evaluation_runs_challenge_id" ON "evaluation_runs" USING btree ("challenge_id");--> statement-breakpoint
CREATE INDEX "idx_evaluation_runs_status" ON "evaluation_runs" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_evaluation_runs_challenge_status" ON "evaluation_runs" USING btree ("challenge_id","status");--> statement-breakpoint
CREATE INDEX "idx_evaluation_runs_started_at" ON "evaluation_runs" USING btree ("started_at");--> statement-breakpoint
CREATE INDEX "idx_google_accounts_user_id" ON "google_accounts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_meeting_analyses_meeting_id" ON "meeting_analyses" USING btree ("sync_meeting_id");--> statement-breakpoint
CREATE INDEX "idx_meeting_analyses_status" ON "meeting_analyses" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_meeting_participants_meeting_id" ON "meeting_participants" USING btree ("sync_meeting_id");--> statement-breakpoint
CREATE INDEX "idx_meeting_participants_user_id" ON "meeting_participants" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_meeting_participants_google_user_id" ON "meeting_participants" USING btree ("google_user_id");--> statement-breakpoint
CREATE INDEX "idx_meeting_utterances_meeting_id" ON "meeting_utterances" USING btree ("sync_meeting_id");--> statement-breakpoint
CREATE INDEX "idx_meeting_utterances_participant_id" ON "meeting_utterances" USING btree ("participant_id");--> statement-breakpoint
CREATE INDEX "idx_meeting_utterances_start_time" ON "meeting_utterances" USING btree ("sync_meeting_id","start_time");--> statement-breakpoint
CREATE INDEX "idx_refresh_tokens_user_id" ON "refresh_tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_refresh_tokens_expires_at" ON "refresh_tokens" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "idx_repos_project_id" ON "repos" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "idx_repos_external_repo_id" ON "repos" USING btree ("external_repo_id");--> statement-breakpoint
CREATE INDEX "idx_sync_meetings_challenge_id" ON "sync_meetings" USING btree ("challenge_id");--> statement-breakpoint
CREATE INDEX "idx_sync_meetings_status" ON "sync_meetings" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_sync_meetings_end_time" ON "sync_meetings" USING btree ("end_time");--> statement-breakpoint
CREATE INDEX "idx_sync_meetings_end_time_status" ON "sync_meetings" USING btree ("end_time","status");--> statement-breakpoint
CREATE INDEX "idx_sync_meetings_created_by" ON "sync_meetings" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "idx_sync_meetings_conference_record_id" ON "sync_meetings" USING btree ("conference_record_id");--> statement-breakpoint
CREATE INDEX "idx_task_assignees_task_id" ON "task_assignees" USING btree ("task_id");--> statement-breakpoint
CREATE INDEX "idx_task_assignees_user_id" ON "task_assignees" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_task_assignees_composite" ON "task_assignees" USING btree ("task_id","user_id");--> statement-breakpoint
CREATE INDEX "idx_task_workspaces_task_id" ON "task_workspaces" USING btree ("task_id");--> statement-breakpoint
CREATE INDEX "idx_task_workspaces_repo_id" ON "task_workspaces" USING btree ("repo_id");--> statement-breakpoint
CREATE INDEX "idx_task_workspaces_composite" ON "task_workspaces" USING btree ("task_id","repo_id");--> statement-breakpoint
CREATE INDEX "idx_tasks_challenge_id" ON "tasks" USING btree ("challenge_id");--> statement-breakpoint
CREATE INDEX "idx_tasks_parent_task_id" ON "tasks" USING btree ("parent_task_id");--> statement-breakpoint
CREATE INDEX "idx_tasks_challenge_status" ON "tasks" USING btree ("challenge_id","status");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_users_github_username" ON "users" USING btree ("github_username");